name: QuakeSolo_Serv
main: com.geekpower14.quake
version: 1.0.0
author: Geekpower14
website: http://geekpower14.com/
depend: [SamaGamesAPI]
commands:
   q:
      description: Quake Command
      aliases: [quake]